// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate_swagger = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "junmin.hong",
            "url": "https://github.com/junminhong",
            "email": "junminhong1110@gmail.com"
        },
        "license": {
            "name": "MIT",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/short-url": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "short-url"
                ],
                "summary": "縮短網址",
                "parameters": [
                    {
                        "type": "string",
                        "default": "Bearer \u003c請在這邊輸入Atomic Token\u003e",
                        "description": "Atomic Token",
                        "name": "Authorization",
                        "in": "header"
                    },
                    {
                        "description": "請求資料",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requester.ShortenUrl"
                        }
                    }
                ],
                "responses": {
                    "1001": {
                        "description": "短連結生成失敗",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "1002": {
                        "description": "短連結生成成功",
                        "schema": {
                            "$ref": "#/definitions/responser.Response"
                        }
                    },
                    "1003": {
                        "description": "無效連結",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "requester.ShortenUrl": {
            "type": "object",
            "required": [
                "source_url"
            ],
            "properties": {
                "source_url": {
                    "type": "string"
                }
            }
        },
        "responser.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "message": {
                    "type": "string"
                },
                "result_code": {
                    "type": "integer"
                },
                "time_stamp": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "JWT": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo_swagger holds exported Swagger Info so clients can modify it
var SwaggerInfo_swagger = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:9020",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Thrurl API",
	Description:      "一個簡單易用且強大的縮網址服務",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate_swagger,
}

func init() {
	swag.Register(SwaggerInfo_swagger.InstanceName(), SwaggerInfo_swagger)
}
